steps:
  # Step 1: Configurar credenciais para o Git
  - name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "https://${GIT_TOKEN}:@github.com" > /root/.git-credentials
        git config --global credential.helper 'store --file=/root/.git-credentials'
        git config --global url."https://${GIT_TOKEN}:@github.com/".insteadOf "https://github.com/"

  # Step 2: Checkout do código do repositório do GitHub
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/usuario/repositorio.git']

  # Step 3: Navegar até o diretório do projeto Dataform (se necessário)
  - name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - 'cd /workspace/repositorio/dataform'

  # Step 4: Instalar dependências do Dataform
  - name: 'docker://dataformco/dataform:1.6.11'
    args: ['install']

  # Step 5: Rodar o comando de compilação do Dataform
  - name: 'docker://dataformco/dataform:1.6.11'
    args: ['compile']

  # Step 6: Executar validação ou testes (opcional)
  - name: 'docker://dataformco/dataform:1.6.11'
    args: ['run']

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY

