substitutions:
    _APPLY_CHANGES: 'false'
    _ENV: 'prod'
    _REGION: 'us-central1'
    _DATAFORM_EXECUTOR_WORKFLOW: 'não criei um workflow'
steps:
- id: 'DATAFORM - [Compile/Run + Check status]'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      if [ "${_APPLY_CHANGES}" = 'true' ]; then
        echo "*****************************************"
        echo "Running Dataform on live environment"
        echo "*****************************************"
        dataform_compile_only=false
      else
        echo "*****************************************"
        echo "DRY RUN : Compiling Dataform only"
        echo "*****************************************"
        dataform_compile_only=true
      fi

      echo "Skipping Dataform workflow execution as no workflow is configured."
      
      # You can add additional commands here if needed

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
timeout: 3600s
