steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Checking out code..."
        git clone https://github.com/RodrigoKartcheski/dataform.git
        cd dataform

  - name: 'dataformco/dataform:1.6.11'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installing project dependencies..."
        dataform install

  - name: 'dataformco/dataform:1.6.11'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running dataform compile..."
        dataform compile

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
timeout: 3600s

